// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProEventos.API.Data;

namespace ProEventos.API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220609030320_SqliteContext")]
    partial class SqliteContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("ProEventos.API.Models.Auditoriums", b =>
                {
                    b.Property<int>("IdAuditorium")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasBusesToTransportVisitors")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocationAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("IdAuditorium");

                    b.ToTable("Auditoriums");
                });

            modelBuilder.Entity("ProEventos.API.Models.Events", b =>
                {
                    b.Property<int>("IdEvent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateOfTheEvent")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlyerPictureFile")
                        .HasColumnType("TEXT");

                    b.Property<string>("LotOfEvent")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfPeople")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThemeOfEvent")
                        .HasColumnType("TEXT");

                    b.HasKey("IdEvent");

                    b.ToTable("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
